# Generated by Django 6.0.1 on 2026-01-31 14:56

import django.core.validators
import django.db.models.deletion
import todolist_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=todolist_app.models.product_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='圖片')),
                ('thumbnail150', models.ImageField(blank=True, upload_to=todolist_app.models.product_thumbnail150_upload_path, verbose_name='縮圖 150x150')),
                ('thumbnail800', models.ImageField(blank=True, upload_to=todolist_app.models.product_thumbnail800_upload_path, verbose_name='縮圖 800x800')),
                ('isPrimary', models.BooleanField(default=False, verbose_name='主圖')),
                ('displayOrder', models.PositiveIntegerField(default=0, verbose_name='顯示順序')),
                ('altText', models.CharField(blank=True, max_length=255, verbose_name='替代文字')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todolist_app.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品圖片',
                'verbose_name_plural': '商品圖片',
                'ordering': ['displayOrder', 'uploadedAt'],
            },
        ),
    ]
