# Generated by Django 6.0.1 on 2026-02-01 06:12

import django.core.validators
import django.db.models.deletion
import todolist_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=todolist_app.models.category_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('thumbnail150', models.ImageField(blank=True, upload_to=todolist_app.models.category_thumbnail150_upload_path)),
                ('thumbnail800', models.ImageField(blank=True, upload_to=todolist_app.models.category_thumbnail800_upload_path)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todolist_app.category')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
                'ordering': ['displayOrder', 'categoryName'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='todolist_app.category'),
        ),
    ]
