# Generated by Django 6.0.1 on 2026-02-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0008_add_mptt_fields_and_populate'),
    ]

    operations = [
        # No-op migration: keep MPTT integer fields in place.
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
